apiVersion: v1
kind: Secret
metadata:
  name: git-https
  namespace: developer-ns
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: mingjiex-vmware
  password: 
