apiVersion: v1
kind: Secret
metadata:
  name: grype-airgap-overlay
  namespace: tap-install #! namespace where tap is installed
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ScanTemplate"}),expects="1+"
    ---
    spec:
      template:
        initContainers:
          #@overlay/match by=overlay.subset({"name": "scan-plugin"}), expects="1+"
          - name: scan-plugin
            #@overlay/match missing_ok=True
            env:
              #@overlay/append
              - name: GRYPE_CHECK_FOR_APP_UPDATE
                value: "false"
              - name: GRYPE_DB_AUTO_UPDATE
                value: "true"
              - name: GRYPE_DB_UPDATE_URL
                value: "https://cli-vm.corp.tanzu/grype/databases/listing.json" #! url points to the internal file server
              - name: GRYPE_DB_CA_CERT
                value: "/etc/ssl/certs/apache-ca-cert.crt"
            volumeMounts:
              #@overlay/append
              - name: harbor-ca-cert
                mountPath: /etc/ssl/certs/harbor-ca-cert.crt
                subPath: ca.crt #! key pointing to ca certificate
              - name: apache-ca-cert
                mountPath: /etc/ssl/certs/apache-ca-cert.crt
                subPath: corp.tanzu.crt #! key pointing to ca certificate
        volumes:
        #@overlay/append
        - name: harbor-ca-cert
          configMap:
            name: harbor-ca-cert #! name of the configmap created
        - name: apache-ca-cert
          configMap:
            name: apache-ca-cert #! name of the configmap created
